# Generated by Django 3.0.1 on 2020-02-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpis',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
