# Generated by Django 3.0.1 on 2020-02-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0002_wpis_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpis',
            name='thumb',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
