# Generated by Django 3.0.1 on 2020-02-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0003_auto_20200215_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpis',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
